hamma/urls.py
from django.urls import path
from hamma import views

app_name = 'hamma'

urlpatterns=[
    path('signup/',views.signup,name='signup'),
    path('user_login/',views.user_login,name='user_login'),
    path('app/', views.app, name='app'),
]

tool/urls.py
from django.contrib import admin
from django.urls import path, include

from hamma import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('special/',views.special,name='special'),
    path('hamma/',include('hamma.urls')),
    path('logout/', views.user_logout, name='logout'),
]

hamma/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Usuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username

hamma/forms.py
from django import forms
from hamma.models import Usuario
from django.contrib.auth.models import User

class Formulario(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
        model = User
        fields = ('username','password','email')

class Usuario(forms.ModelForm):
     
    class Meta():
        model = Usuario
        fields = ('portfolio_site','profile_pic')

hamma/views.py
from django.shortcuts import render
from hamma.forms import Usuario, Formulario
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(request):
    return render(request,'hamma/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = Formulario(data=request.POST)
        profile_form = Usuario(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = Formulario()
        profile_form = Usuario()
    return render(request,'hamma/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'hamma/login.html', {})

def app(request):
    return render(request, 'hamma/ok.html', {})

templates/hamma/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Top</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Keep Pushing</a></li>
          <li><a class="navbar-link" href="{% url 'hamma:signup' %}">Sign Up</a></li>     
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'hamma:user_login' %}">Login</a></li>
          {% endif %}
</ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
  </body>
</html>

templates/hamma/index.html
{% extends "hamma/base.html" %}
{% block body_block %}
<style>
  .tf {
    font-family: Ink Free;
    text-align: center;
    font-size: 55px;
    border-radius: 15px;
    border: 2px solid rgba(21, 209, 37, 0.63);
    padding: 10px;
  }
</style>

<div class="container">
  <div class="jumbotron">
    <div class="tf">Who tf r u?</div>
    {% if user.is_authenticated %}
        <h2>Hello {{ user.username }}</h2>
        {{ view.app }}
    {% else %}
        <h2>Sign up or Login to see what's up</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/hamma/login.html
{% extends 'hamma/base.html' %}
{% block body_block %}
<style>
  .tf {
    font-family: Ink Free;
    text-align: center;
    font-size: 55px;
    border-radius: 15px;
    border: 2px solid rgba(21, 209, 37, 0.63);
    padding: 10px;
  }
  .ft {
    font-family: Ink Free;
    font-size: 25px;
  }
</style>

  <div class="container">
    <div class="jumbotron">
      <h1 class="tf">Login here :</h1>
<form method="post" action="{% url 'hamma:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username" class="ft">Username:</label>
          <input type="text" name="username" placeholder="Username">
<label for="password" class="ft">Password:</label>
          <input type="password" name="password" placeholder="Password">
<input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

templates/hamma/ok.html
ok

templates/hamma/registration.html
{% extends "hamma/base.html" %}
{% load static %}
{% block body_block %}
<style>
  .tf {
    font-family: Ink Free;
    text-align: center;
    font-size: 55px;
    border-radius: 15px;
    border: 2px solid rgba(21, 209, 37, 0.63);
    padding: 10px;
  }
  .ft {
    font-family: Ink Free;
    text-align: center;
    font-size: 25px;
  }
  .tft {
    font-family: Ink Free;
    font-size: 25px;
    border-radius: 15px;
    border: 2px solid rgba(21, 209, 37, 0.63);
    padding: 10px;
  }
</style>

  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1 class="ft">Thank you for registering!</h1>
      {% else %}
        <h1 class="tf">Keep Pushing Sign Up</h1><br>
        <h3 class="ft">Just fill out the form.</h3><br>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          <div class="tft">
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
        </div><br>
          <input type="submit" name="" value="Sign Up">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}